function fig=PlotFig(N,date1,rating1,date2,rating2,Xmin,Xmax,Ymin,Ymax,...
    Y0,Xs,Xt,Rmin,Rmax,y,Yt,SR,DR,Title)

fig=figure(N);
AX = axes('Parent',fig);
hold on;
H1 = plot(date1, rating1);
H2 = plot(date2, rating2);

% set(AX(1),'Position',[0.03 0.03 0.28 0.29]);
set(AX(1),'XLim',[Xmin Xmax]);
set(AX(1),'YLim',[Ymin Ymax]);
set(AX(1),'LineWidth',2);
set(AX(1),'box','on');
set(AX(1),'XColor','k','YColor','k');
set(AX(1),'XTick',datenum(Y0,1:Xs:Xt+Xs,1));
set(AX(1),'XTickLabel',{datestr(datenum(Y0,1:Xs:Xt+Xs,1),12)});
set(AX(1),'YTick',Rmin:y:Rmax);
set(AX(1),'YTickLabel',{Yt}');
set(AX(1),'FontName','Arial');
% set(AX(1),'XGrid','on');
set(AX(1),'YGrid','on');
% xlabel('Date','FontSize',15);
ylabel('Rating','FontSize',25)
title(Title,'FontSize',25);

set(AX(1),'FontSize',15);

set(H1,...
    'LineStyle','--',...
    'Linewidth',2.2,...
    'Color',[0.6 0.6 1],...
    'Marker','x',...
    'MarkerEdgeColor',[0.25 0.25 0.75],...
    'MarkerSize',18,...
    'DisplayName',[' Single   ' SR]);

set(H2,...
    'LineStyle','--',...
    'Linewidth',2.2,...
    'Color',[1 0.6 0.6],...
    'Marker','+',...
    'MarkerEdgeColor',[0.75 0.25 0.25],...
    'MarkerSize',16,...
    'DisplayName',[' Double  ' DR]);

L1 = legend(AX,'show');
% legend(AX,'boxoff');
set(L1,'FontSize',20,...
    'Linewidth',1.8,...
    'EdgeColor',[0.5 0.5 0.5],...
    'Color',[0.5 0.5 0.5],...    
    'Position',[0.66 0.693 0.24 0.2]);
%    'Position',[0.26 0.693 0.24 0.2]);

set(fig, 'PaperType','a4',...
    'PaperOrientation','landscape', ...
    'PaperPositionMode','manual',...
    'PaperUnits','points',...
    'PaperPosition',[-31.5 -2.5 902 572]);
end

